### ISSUE TITLE
Possible improvement for loading...

### ISSUE THREAD

**Issue by rpgoldman** [bendudson/py4cl#14]
py4cl.asd has this:

``` lisp
(defparameter py4cl/config:*base-directory* 
    (make-pathname :name nil :type nil :defaults *load-truename*))
```
but you could use `asdf:system-source-directory` as an alternative.  `*load-truename* can be exciting because of differences between CL implementations, but Faré seems to have sussed them all out...

**Comment by bendudson** [comment]
Thanks very much! I've made this change in PR #17

**Comment by rpgoldman** [comment]
Glad I could help!
