### ISSUE TITLE
How does this compare vs. burgled-batteries?

### ISSUE THREAD

**Issue by jnc-nj** [bendudson/py4cl#16]
This seems to do much the same; just curious, are there any details you're willing to give concerning the implementation? And whether there are any advantages to using this package?

I find the interface to be a lot nicer, btw.

**Comment by bendudson** [comment]
There was some discussion of this on Reddit [here](https://www.reddit.com/r/Common_Lisp/comments/brg7s8/bendudsonpy4cl_call_python_from_common_lisp/) and [here](https://www.reddit.com/r/Common_Lisp/comments/c5lt6z/comparing_burgledbatteries3_and_py4cl/). 

I looked into using burgled batteries before starting this, but it had limitations like python code calling lisp functions which I needed. I was not comfortable enough with FFI at the time (still not), and thought that debugging streams would be easier than dealing with libraries and segfaults when things went wrong. Of course the complexity goes somewhere, but it was easier (for me) to start with streams. I think one advantage is that it works with pretty much all versions of python (2.7+ & 3); as long as it can find the executable then it should work. Supporting multiple different CPython library versions seemed harder (but perhaps is not). 

Glad you find the interface nicer, thanks! Much of what is good is thanks to @kat-co 's `chain` suggestions.
@digikar99 is currently making some big changes / improvements, which should speed up the handling of large arrays among other things.

**Comment by digikar99** [comment]
I recently added some more documentation - checkout [Highlights and Limitations of py4cl](https://digikar99.github.io/py4cl/#highlights-and-limitations-of-py4cl). You can check that out to see if `py4cl` meets your needs.

**Comment by jnc-nj** [comment]
> I recently added some more documentation - checkout [Highlights and Limitations of py4cl](https://digikar99.github.io/py4cl/#highlights-and-limitations-of-py4cl). You can check that out to see if `py4cl` meets your needs.

Ah that's perfect, thanks for the replies!
