### ISSUE TITLE
How to handle with the TRY and EXCEPT statement use PY4CL?

### ISSUE THREAD

**Issue by cl-03** [bendudson/py4cl#42]
the PYTHON codes bellow:
```
try:
    c = driver.find_element_by_xpath("//*[@class='el-dialog captchaDilaog']")
    print("exist")
except:
    print("no")
```
using py4cl with errors:
```
(defparameter flag (let ((str1 "//*[@class='el-dialog captchaDilaog']")
			 (str2 "exist")
			 (str3 "no"))
		     (py4cl:python-call
 "try:
    c = driver.find_element_by_xpath("(py4cl::pythonize str1) ")
    flag = " (py4cl::pythonize str2)
"except:
    flag = "(py4cl::pythonize str3 ))))
```
or the other form also error:
```
(defparameter flag (py4cl:python-eval
 "try:
    c = driver.find_element_by_xpath(\"//*[@class='el-dialog captchaDilaog']\")    flag = \"exist\"
except:
    flag = \"no\""))
```

**Comment by cl-03** [comment]
Can py4cl deal with this situation?

**Comment by digikar99** [comment]
Apologies, been busy with other tasks. You might also find the [documentation of py4cl2](https://digikar99.github.io/py4cl2/#doing-arbitrary-things-in-python) useful, particularly this part:

> Unlike lisp, python (and most other languages) make a distinction between *statements* and *expressions*: see [Quora](https://www.quora.com/Whats-the-difference-between-a-statement-and-an-expression-in-Python-Why-is-print-%E2%80%98hi%E2%80%99-a-statement-while-other-functions-are-expressions) or [stackoverflow](https://stackoverflow.com/questions/4728073/what-is-the-difference-between-an-expression-and-a-statement-in-python).
> 
> A general rule of thumb from there is: if you can print it, or assign it to a variable, then it's an expression, otherwise it's a statement.
> 
> Both `pyeval` and `pyexec` take any type of arguments. The `arg` is `pythonize`d if the `arg` is not a `string`, or it is a `string` that can be read into a `real`.

As far as I understand python, since try...except is a statement(s) rather than expression, that part cannot be eval-ed; so, you'd probably want to deal directly with this:

```lisp
(defparameter flag 
           (handler-case 
               (progn
                 ;; depending on your performance requirements, 
                 ;; you could also store the driver on lisp side (slowest) and call the method using py4cl:python-method
                 (py4cl:python-eval "driver.find_element_by_xpath(\"//*[@class='el-dialog captchaDilaog']\")")
                 "exist")
             (py4cl:python-error (condition)
               (declare (ignore condition))
               "no")))
```

Either that way, or by converting the block of statements into a function (fastest) and then calling that function using python-eval or python-call.

**Comment by cl-03** [comment]
It doesn't matter and give a thanks to you,Let me have a try later,thanks.

**Comment by cl-03** [comment]
It has been handled At last like bellow:
```
 (py4cl:python-evec
"try:
    c = driver.find_element_by_xpath(\"//*[@class='el-dialog captchaDilaog']\")
    print(\"exist\")
except:
    print(\"no\")"
```
Thank you for your kindness。
